spring:
  application:
    name: greeting-microservice

# Configuración del servidor (Puerto 8001)
server:
  port: 8001

# Configuración de Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/